[package]
name = "os"
version = "0.1.0"
edition = "2018"
authors = ["Abel van Hulst <abelvanhulst@gmail.com>", "and everyone else who has worked on this project on GitHub"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]